# Generated by Django 6.0 on 2025-12-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nohp', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('jurusan', models.CharField(max_length=50)),
            ],
        ),
    ]
